s1 = input ('Вы ввели строку s1: ')
s2 = input ('Вы ввели строку s2: ')
print ('Длина строки s1 равна:', len (s1))
print ('Длина строки s2 равна:', len (s2))
print ('Первый символ первой строки:', s1 [0])
print ('Последний символ последней строки:', s2 [-1])
print ('Does s1 equal to s2?',s1==s2)
print ('Is there s1 in s2?',s1 in s2)
print ('Vice versa?',s2 in s1)